config/routes.rb
Rails.application.routes.draw do
  resources :lending_sets
  resources :lending_statuses
  resources :customers
  resources :customers, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :book_stocks, except: %w[export] do
    collection { get :export }
  end
  resources :book_stocks
  resources :book_stocks, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :book_stock_statuses
  resources :authors
  resources :authors, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :book_masters
  resources :book_masters, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :ndc_categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/lending_set.rb
class LendingSet < ApplicationRecord
  def self.ransackable_attributes(_auth_object = nil)
    %w[customer_id book_stock_id lending_status_id lend_start_date return_deadline_date return_date memo id created_at
       updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[book_stocks customer lending lending_status]
  end

  after_save do
    if lending_status.name === "貸出中"
      book_stocks.each do |bs|
        bs.book_stock_status_id = 2
        bs.save
      end
    elsif lending_status.name === "返却済"
      book_stocks.each do |bs|
        bs.book_stock_status_id = 1
        bs.save
      end
    end
  end

  validates :book_stocks, presence: true
  validates :lend_start_date, presence: true, date: true
  validates :return_deadline_date, presence: true, date: { after: :lend_start_date }
  validates :return_date, date: { allow_blank: true }

  belongs_to :customer
  belongs_to :lending_status

  has_many :lending
  has_many :book_stocks, through: :lending
end

app/controllers/lending_sets_controller.rb
class LendingSetsController < ApplicationController
  include Pagy::Backend
  before_action :set_lending_set, only: %i[show edit update destroy]

  # GET /lending_sets
  def index
    @lending_sets = LendingSet
      .eager_load(:customer)
      .eager_load(:lending_status)
    @q = @lending_sets.ransack(params[:q])
    @q.sorts = "id asc" if @q.sorts.empty?
    @pagy, @lending_sets = pagy(@q.result, page: params[:page], items: params[:items])
  end

  # GET /lending_sets/1
  def show
  end

  # GET /lending_sets/new
  def new
    @lending_set = LendingSet.new
  end

  # GET /lending_sets/1/edit
  def edit
  end

  # POST /lending_sets
  def create
    @lending_set = LendingSet.new(lending_set_params)

    if @lending_set.save
      redirect_to @lending_set, notice: t("controller.create.success", model: LendingSet.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /lending_sets/1
  def update
    if @lending_set.update(lending_set_params)
      redirect_to @lending_set, notice: t("controller.edit.success", model: LendingSet.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /lending_sets/1
  def destroy
    @lending_set.destroy!
    redirect_to lending_sets_url, notice: t("controller.destroy.success", model: LendingSet.model_name.human)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_lending_set
      @lending_set = LendingSet
        .eager_load(:customer)
        .eager_load(:lending_status)
        .find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lending_set_params
      params.require(:lending_set).permit(:customer_id, :lending_status_id, :lend_start_date, :return_deadline_date,
                                          :return_date, :memo, { book_stock_ids: [] })
    end
end

app/helpers/lending_sets_helper.rb
module LendingSetsHelper
  include Pagy::Frontend
end

app/views/lending_sets/_form.html.erb
<%= form_with(model: lending_set, html: { class: %w[form-control form-control-sm] }) do |form| -%>
  <%- if lending_set.errors.any? -%>
  <div style="color: red">
    <h2><%= t("errors.template.header", model: LendingSet.model_name.human, count: lending_set.errors.count) %></h2>

    <ul>
    <% lending_set.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <%- end -%>
    </ul>
  </div>
  <%- end -%>

  <%- if lending_set.persisted? -%>
  <div>
    <%= form.label :id, style: "display: block" %>
    <div class="ps-2">
      <%= form.number_field :id, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <%- end -%>
  <div>
    <%= form.label LendingSet.reflect_on_association(:customer).foreign_key %>
    <div class="ps-2">
      <%= form.collection_select(
            LendingSet.reflect_on_association(:customer).foreign_key,
            LendingSet.reflect_on_association(:customer).klass.all,
            :id,
            :name,
            { include_blank: "選択なし" }
          ) %>
    </div>
  </div>
  <div>
    <%= form.label :book_stocks %>
    <div class="ps-2">
      <%= form.collection_select(
            :book_stock_ids,
            BookStock
              .joins(:book_stock_status)
              # 貸し出せないものは非表示
              .where("book_stock_status_id = 1")
                # ただし、この LendingSet で貸し出しているものは表示したい
                .or(BookStock.where(book_stock_status_id: @lending_set.book_stocks.map{|bs| bs.book_stock_status.id}))
              .map {|bs| [bs.id, bs.id.to_s + ":" + bs.book_master.title]},
            :first,
            :last,
            { multiple: true }
          ) %>
    </div>
  </div>
  <div>
    <%= form.label LendingSet.reflect_on_association(:lending_status).foreign_key %>
    <div class="ps-2">
      <%= form.collection_select(
            LendingSet.reflect_on_association(:lending_status).foreign_key,
            LendingSet.reflect_on_association(:lending_status).klass.all,
            :id,
            :name,
            { include_blank: "選択なし" }
          ) %>
    </div>
  </div>
  <div>
    <%= form.label :lend_start_date, style: "display: block" %>
    <div class="ps-2">
      <%= form.date_field :lend_start_date, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <div>
    <%= form.label :return_deadline_date, style: "display: block" %>
    <div class="ps-2">
      <%= form.date_field :return_deadline_date, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <div>
    <%= form.label :return_date, style: "display: block" %>
    <div class="ps-2">
      <%= form.date_field :return_date, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <div>
    <%= form.label :memo, style: "display: block" %>
    <div class="ps-2">
      <%= form.text_area :memo, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <%- if lending_set.persisted? -%>
  <div>
    <%= form.label :created_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :created_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <div>
    <%= form.label :updated_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :updated_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <%- end -%>
  <div>
    <%= form.submit class: %w[btn btn-primary] %>
  </div>
<% end %>

app/views/lending_sets/_lending_set.html.erb
<div id="<%= dom_id lending_set %>">
  <table class="table table-hover">
    <tr>
      <td>
        <strong>Id:</strong>
      </td>
      <td>
        <%= lending_set.id %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= LendingSet.human_attribute_name(:customer_id) %>
        </strong>
      </td>
      <td>
        <%= lending_set.customer.name %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= LendingSet.human_attribute_name(:book_stocks) %>
        </strong>
      </td>
      <td>
        <%= lending_set.book_stocks.map{|bs| bs.id.to_s + ":" + bs.book_master.title}.join(", ") %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= LendingSet.human_attribute_name(:lending_status_id) %>
        </strong>
      </td>
      <td>
        <%= lending_set.lending_status.name %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= LendingSet.human_attribute_name(:lend_start_date) %>
        </strong>
      </td>
      <td>
        <%= lending_set.lend_start_date && l(lending_set.lend_start_date) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= LendingSet.human_attribute_name(:return_deadline_date) %>
        </strong>
      </td>
      <td>
        <%= lending_set.return_deadline_date && l(lending_set.return_deadline_date) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= LendingSet.human_attribute_name(:return_date) %>
        </strong>
      </td>
      <td>
        <%= lending_set.return_date && l(lending_set.return_date) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= LendingSet.human_attribute_name(:memo) %>
        </strong>
      </td>
      <td>
        <%= lending_set.memo %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= LendingSet.human_attribute_name(:created_at) %>
        </strong>
      </td>
      <td>
        <%= lending_set.created_at && l(lending_set.created_at) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= LendingSet.human_attribute_name(:updated_at) %>
        </strong>
      </td>
      <td>
        <%= lending_set.updated_at && l(lending_set.updated_at) %>
      </td>
    </tr>
  </table>
</div>

app/views/lending_sets/edit.html.erb
<h1><%= t("view.edit.title", model: LendingSet.model_name.human) %></h1>
<%= render "form", lending_set: @lending_set %>

<br>

<div>
  <%= link_to t("view.edit.move_to_show", model: LendingSet.model_name.human), @lending_set %> |
  <%= link_to t("view.edit.move_to_index", model: LendingSet.model_name.human.pluralize), lending_sets_path %>
</div>

app/views/lending_sets/index.html.erb
<div style="display: flex;flex-direction: column;height: 100vh;">

  <header class="main-content-header">
    <p style="color: green"><%= notice %></p>

    <h1><%= LendingSet.model_name.human %><%= link_to "", new_lending_set_path, class: %w[bi bi-plus-circle-fill ms-2] %></h1>

  <div class="accordion">
    <div class="accordion-item">
      <h2 class="accordion-header" id="search-form-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#search-form"
          aria-expanded="false"
          aria-controls="search-form"><%= t("view.index.search_condition") %></button>
      </h2>
      <div id="search-form" class="panel panel-default accordion-collapse collapse" aria-labelledby="headingOne">
<%= search_form_for @q, html: { class: %w[form-control form-control-sm], data: { turbo_frame: "list" } } do |f| %>
        <div>
          <%= f.label :id_eq %>
          <div class="ps-2">
            <%= f.number_field :id_eq, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label LendingSet.reflect_on_association(:customer).foreign_key + "_in".to_s %>
          <div class="ps-2">
            <%= f.collection_select(
                  LendingSet.reflect_on_association(:customer).foreign_key + "_in".to_s,
                  LendingSet.reflect_on_association(:customer).klass.all,
                  :id,
                  :name,
                  {},
                  { multiple: true }
                ) %>
          </div>
        </div>
        <div>
          <%= f.label :book_stock.to_s + "_in".to_s %>
          <div class="ps-2">
            <%= f.collection_select(
                  :lending_book_stock_id.to_s + "_in".to_s,
                  BookStock.all.map {|bs| [bs.id, bs.id.to_s + ":" + bs.book_master.title]},
                  :first,
                  :last,
                  {},
                  { multiple: true }
                ) %>
          </div>
        </div>
        <div>
          <%= f.label LendingSet.reflect_on_association(:lending_status).foreign_key + "_in".to_s %>
          <div class="ps-2">
            <%= f.collection_select(
                  LendingSet.reflect_on_association(:lending_status).foreign_key + "_in".to_s,
                  LendingSet.reflect_on_association(:lending_status).klass.all,
                  :id,
                  :name,
                  {},
                  { multiple: true }
                ) %>
          </div>
        </div>
        <div>
          <%= f.label :lend_start_date %>
          <div class="ps-2">
            <%= f.date_field :lend_start_date_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.date_field :lend_start_date_lteq_end_of_day, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :return_deadline_date %>
          <div class="ps-2">
            <%= f.date_field :return_deadline_date_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.date_field :return_deadline_date_lteq_end_of_day, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :return_date %>
          <div class="ps-2">
            <%= f.date_field :return_date_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.date_field :return_date_lteq_end_of_day, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :memo_cont %>
          <div class="ps-2">
            <%= f.search_field :memo_cont, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :created_at %>
          <div class="ps-2">
            <%= f.datetime_field :created_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :created_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :updated_at %>
          <div class="ps-2">
            <%= f.datetime_field :updated_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :updated_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <%= f.hidden_field :limit, id: "f-limit", value: params[:limit] || Pagy::DEFAULT[:limit] %>
        <%= f.submit class: %w[btn btn-primary] %>
        <input
          type="reset"
          class="btn btn-primary"
          onclick="clear_form(arguments[0], this)"
          value="<%= t("helpers.submit.clear") %>">
<%- end -%>
      </div>
    </div>
  </header>

  <main style="flex-grow: 1;flex-shrink: 1;overflow-y: auto;">
<%= turbo_frame_tag "list" do %>
  <div id="lending_sets" class="text-nowrap">
    <table class="table table-hover text-nowrap">
      <thead class="table-light sticky-top">
        <th><%= sort_link(@q, :id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :customer_id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :title, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :lending_status_id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :lend_start_date, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :return_deadline_date, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :return_date, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :memo, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :created_at, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :updated_at, default_order: :asc, class: "d-block") %></th>
        <th><%= t("view.index.operation") %></th>
      </thead>
      <tbody>
  <%- @lending_sets.each do |lending_set| %>
        <tr
          tabindex="0"
          role="button"
          onkeypress="handleEnterKeypressListIten(arguments[0], this, '<%= url_target(nil, lending_set).to_s %>')"
          onclick="handleClickListItem(arguments[0], this, '<%= url_target(nil, lending_set).to_s %>')">
          <td><%= lending_set.id %></td>
          <td><%= lending_set.customer.name %></td>
          <td><%= lending_set.book_stocks.map {|bs| bs.id.to_s + ":" + bs.book_master.title }.join(", ") %></td>
          <td><%= lending_set.lending_status.name %></td>
          <td><%= lending_set.lend_start_date && l(lending_set.lend_start_date) %></td>
          <td><%= lending_set.return_deadline_date && l(lending_set.return_deadline_date) %></td>
          <td><%= lending_set.return_date && l(lending_set.return_date) %></td>
          <td><%= lending_set.memo %></td>
          <td><%= lending_set.created_at && l(lending_set.created_at) %></td>
          <td><%= lending_set.updated_at && l(lending_set.updated_at) %></td>
          <td>
            <%= button_to(
                  t("helpers.submit.delete"),
                  lending_set,
                  method: :delete,
                  tabindex: 0,
                  class: %w[btn btn-primary],
                  onclick: "handleDeleteListItem(arguments[0], this)",
                  data: { turbo_confirm: t("helpers.dialog.delete", id: lending_set.id) }
                ) %>
          </td>
        </tr>
  <%- end %>
      </tbody>
    </table>
  </div>
  <div>
    <%== pagy_bootstrap_nav(@pagy) %>
    <%== pagy_limit_selector_js(@pagy, item_name: "Lending set".pluralize(@pagy.count), id: "pagy-limit-selector") %>
    <%= link_to(
          t("view.index.update_item_per_page", model: LendingSet.model_name.human),
          "javascript:void(0);",
          onClick: "updateItemPerPage(arguments[0],
          this)"
        ) %>
  </div>
<% end %>
  </main>
</div>

app/views/lending_sets/new.html.erb
<h1><%= t("view.new.title", model: LendingSet.model_name.human) %></h1>
<%= render "form", lending_set: @lending_set %>

<br>

<div>
  <%= link_to t("view.new.move_to_index", model: LendingSet.model_name.human.pluralize), lending_sets_path %>
</div>

app/views/lending_sets/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= LendingSet.model_name.human %></h1>

<%= render @lending_set %>

<div>
  <%= link_to t("view.show.move_to_update", model: LendingSet.model_name.human), edit_lending_set_path(@lending_set) %> |
  <%= link_to t("view.show.move_to_index", model: LendingSet.model_name.human.pluralize), lending_sets_path %>

  <%= button_to t("helpers.submit.delete"),
                @lending_set,
                method: :delete,
                class: %w[btn btn-primary],
                data: { turbo_confirm: t("helpers.dialog.delete", id: @lending_set.id) } %>
</div>