config/routes.rb
Rails.application.routes.draw do
  resources :lending_sets
  resources :lending_statuses
  resources :customers
  resources :customers, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :book_stocks, except: %w[export] do
    collection { get :export }
  end
  resources :book_stocks
  resources :book_stocks, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :book_stock_statuses
  resources :authors
  resources :authors, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :book_masters
  resources :book_masters, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :ndc_categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/book_stock.rb
class BookStock < ApplicationRecord
  include CsvImportable

  def self.ransackable_attributes(_auth_object = nil)
    %w[book_master_id book_stock_status_id memo id created_at updated_at]
  end

  belongs_to :book_master
  belongs_to :book_stock_status

  has_many :lending
  has_many :lending_sets, through: :lending
end

app/controllers/book_stocks_controller.rb
class BookStocksController < ApplicationController
  include Pagy::Backend
  before_action :set_book_stock, only: %i[show edit update destroy]

  # GET /book_stocks
  def index
    @book_stocks = BookStock
      .eager_load(:book_master)
      .eager_load(:book_stock_status)
    @q = @book_stocks.ransack(params[:q])
    @q.sorts = "id asc" if @q.sorts.empty?
    @pagy, @book_stocks = pagy(@q.result, page: params[:page], items: params[:items])
  end

  # GET /book_stocks/1
  def show
  end

  # GET /book_stocks/new
  def new
    @book_stock = BookStock.new
  end

  # GET /book_stocks/1/edit
  def edit
  end

  # POST /book_stocks
  def create
    @book_stock = BookStock.new(book_stock_params)

    if @book_stock.save
      redirect_to @book_stock, notice: t("controller.create.success", model: BookStock.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /book_stocks/1
  def update
    if @book_stock.update(book_stock_params)
      redirect_to @book_stock, notice: t("controller.edit.success", model: BookStock.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /book_stocks/1
  def destroy
    @book_stock.destroy!
    redirect_to book_stocks_url, notice: t("controller.destroy.success", model: BookStock.model_name.human)
  end

  # POST /book_stocks_bulk_insert
  def bulk_insert
    if params[:file].nil?
      redirect_to book_stocks_url
      return
    end

    errors = BookStock.csv_import(
      params[:file],
      parser,
      { "書籍" => "book_master_id", "在庫状態" => "book_stock_status_id", "備考" => "memo"},
      {},
      {"書籍" => { parent: BookMaster, search_column_name: :title}, "在庫状態" => { parent: BookStockStatus, search_column_name: :name}}
    )

    if errors.empty?
      flash.notice = t("controller.create.success", model: BookStock.model_name.human)
    else
      flash.alert = errors
    end

    redirect_to book_stocks_url
  end

  # GET /book_stocks/export
  def export
    @book_stocks = BookStock
      .eager_load(lending_sets: :customer)
      .eager_load(:book_master)
      .eager_load(:book_stock_status)
      .order("book_stocks.id, lending_sets.created_at desc")
    respond_to do |format|
      format.csv do
        send_data render_to_string, filename: 'book_stocks.csv', type: :csv
        @q = @book_stocks.ransack(params[:q])
        @q.sorts = "id asc" if @q.sorts.empty?
      end
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_book_stock
      @book_stock = BookStock
        .eager_load(:book_master)
        .eager_load(:book_stock_status)
        .find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_stock_params
      params.require(:book_stock).permit(:book_master_id, :book_stock_status_id, :memo)
    end

    def parser
      Csv::CsvParser
    end
end

app/helpers/book_stocks_helper.rb
module BookStocksHelper
  include Pagy::Frontend
end

app/views/book_stocks/_book_stock.html.erb
<div id="<%= dom_id book_stock %>">
  <table class="table table-hover">
    <tr>
      <td>
        <strong>Id:</strong>
      </td>
      <td>
        <%= book_stock.id %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= BookStock.human_attribute_name(:book_master_id) %>
        </strong>
      </td>
      <td>
        <%= book_stock.book_master.title %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= BookStock.human_attribute_name(:book_stock_status_id) %>
        </strong>
      </td>
      <td>
        <%= book_stock.book_stock_status.name %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= BookStock.human_attribute_name(:memo) %>
        </strong>
      </td>
      <td>
        <%= book_stock.memo %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= BookStock.human_attribute_name(:created_at) %>
        </strong>
      </td>
      <td>
        <%= book_stock.created_at && l(book_stock.created_at) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= BookStock.human_attribute_name(:updated_at) %>
        </strong>
      </td>
      <td>
        <%= book_stock.updated_at && l(book_stock.updated_at) %>
      </td>
    </tr>
  </table>
</div>

app/views/book_stocks/_form.html.erb
<%= form_with(model: book_stock, html: { class: %w[form-control form-control-sm] }) do |form| -%>
  <%- if book_stock.errors.any? -%>
  <div style="color: red">
    <h2><%= t("errors.template.header", model: BookStock.model_name.human, count: book_stock.errors.count) %></h2>

    <ul>
    <% book_stock.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <%- end -%>
    </ul>
  </div>
  <%- end -%>

  <%- if book_stock.persisted? -%>
  <div>
    <%= form.label :id, style: "display: block" %>
    <div class="ps-2">
      <%= form.number_field :id, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <%- end -%>
  <div>
    <%= form.label BookStock.reflect_on_association(:book_master).foreign_key %>
    <div class="ps-2">
      <%= form.collection_select(
            BookStock.reflect_on_association(:book_master).foreign_key,
            BookStock.reflect_on_association(:book_master).klass.all,
            :id,
            :title,
            { include_blank: "選択なし" }
          ) %>
    </div>
  </div>
  <div>
    <%= form.label BookStock.reflect_on_association(:book_stock_status).foreign_key %>
    <div class="ps-2">
      <%= form.collection_select(
            BookStock.reflect_on_association(:book_stock_status).foreign_key,
            BookStock.reflect_on_association(:book_stock_status).klass.all,
            :id,
            :name,
            { include_blank: "選択なし" }
          ) %>
    </div>
  </div>
  <div>
    <%= form.label :memo, style: "display: block" %>
    <div class="ps-2">
      <%= form.text_area :memo, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <%- if book_stock.persisted? -%>
  <div>
    <%= form.label :created_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :created_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <div>
    <%= form.label :updated_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :updated_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <%- end -%>
  <div>
    <%= form.submit class: %w[btn btn-primary] %>
  </div>
<% end %>

app/views/book_stocks/edit.html.erb
<h1><%= t("view.edit.title", model: BookStock.model_name.human) %></h1>
<%= render "form", book_stock: @book_stock %>

<br>

<div>
  <%= link_to t("view.edit.move_to_show", model: BookStock.model_name.human), @book_stock %> |
  <%= link_to t("view.edit.move_to_index", model: BookStock.model_name.human.pluralize), book_stocks_path %>
</div>

app/views/book_stocks/index.html.erb
<div style="display: flex;flex-direction: column;height: 100vh;">

  <header class="main-content-header">
    <p style="color: green"><%= notice %></p>

    <h1><%= BookStock.model_name.human %><%= link_to "", new_book_stock_path, class: %w[bi bi-plus-circle-fill ms-2] %></h1>

    <div id="flashes">
      <%= render partial: "flash", locals: {model: Author} %>
    </div>

    <%= link_to(
          BookStock.model_name.human + " CSV 出力",
          export_book_stocks_path(format: :csv),
        ) %>

    <%= form_tag bulk_insert_book_stocks_path, multipart: true do %>
      <%= label_tag "CSVインポート:" %>
      <%= file_field_tag :file, accept: "text/csv" %>
      <%= submit_tag "インポート", class: %w[btn btn-primary] %>
    <% end %>

  <div class="accordion">
    <div class="accordion-item">
      <h2 class="accordion-header" id="search-form-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#search-form"
          aria-expanded="false"
          aria-controls="search-form"><%= t("view.index.search_condition") %></button>
      </h2>
      <div id="search-form" class="panel panel-default accordion-collapse collapse" aria-labelledby="headingOne">
<%= search_form_for @q, html: { class: %w[form-control form-control-sm], data: { turbo_frame: "list" } } do |f| %>
        <div>
          <%= f.label :id_eq %>
          <div class="ps-2">
            <%= f.number_field :id_eq, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label BookStock.reflect_on_association(:book_master).foreign_key + "_in".to_s %>
          <div class="ps-2">
            <%= f.collection_select(
                  BookStock.reflect_on_association(:book_master).foreign_key + "_in".to_s,
                  BookStock.reflect_on_association(:book_master).klass.all,
                  :id,
                  :title,
                  {},
                  { multiple: true }
                ) %>
          </div>
        </div>
        <div>
          <%= f.label BookStock.reflect_on_association(:book_stock_status).foreign_key + "_in".to_s %>
          <div class="ps-2">
            <%= f.collection_select(
                  BookStock.reflect_on_association(:book_stock_status).foreign_key + "_in".to_s,
                  BookStock.reflect_on_association(:book_stock_status).klass.all,
                  :id,
                  :name,
                  {},
                  { multiple: true }
                ) %>
          </div>
        </div>
        <div>
          <%= f.label :memo_cont %>
          <div class="ps-2">
            <%= f.search_field :memo_cont, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :created_at %>
          <div class="ps-2">
            <%= f.datetime_field :created_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :created_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :updated_at %>
          <div class="ps-2">
            <%= f.datetime_field :updated_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :updated_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <%= f.hidden_field :limit, id: "f-limit", value: params[:limit] || Pagy::DEFAULT[:limit] %>
        <%= f.submit class: %w[btn btn-primary] %>
        <input
          type="reset"
          class="btn btn-primary"
          onclick="clear_form(arguments[0], this)"
          value="<%= t("helpers.submit.clear") %>">
<%- end -%>
      </div>
    </div>
  </header>

  <main style="flex-grow: 1;flex-shrink: 1;overflow-y: auto;">
<%= turbo_frame_tag "list" do %>
  <div id="book_stocks" class="text-nowrap">
    <table class="table table-hover text-nowrap">
      <thead class="table-light sticky-top">
        <th><%= sort_link(@q, :id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :book_master_id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :book_stock_status_id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :memo, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :created_at, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :updated_at, default_order: :asc, class: "d-block") %></th>
        <th><%= t("view.index.operation") %></th>
      </thead>
      <tbody>
  <%- @book_stocks.each do |book_stock| %>
        <tr
          tabindex="0"
          role="button"
          onkeypress="handleEnterKeypressListIten(arguments[0], this, '<%= url_target(nil, book_stock).to_s %>')"
          onclick="handleClickListItem(arguments[0], this, '<%= url_target(nil, book_stock).to_s %>')">
          <td><%= book_stock.id %></td>
          <td><%= book_stock.book_master.title %></td>
          <td><%= book_stock.book_stock_status.name %></td>
          <td><%= book_stock.memo %></td>
          <td><%= book_stock.created_at && l(book_stock.created_at) %></td>
          <td><%= book_stock.updated_at && l(book_stock.updated_at) %></td>
          <td>
            <%= button_to(
                  t("helpers.submit.delete"),
                  book_stock,
                  method: :delete,
                  tabindex: 0,
                  class: %w[btn btn-primary],
                  onclick: "handleDeleteListItem(arguments[0], this)",
                  data: { turbo_confirm: t("helpers.dialog.delete", id: book_stock.id) }
                ) %>
          </td>
        </tr>
  <%- end %>
      </tbody>
    </table>
  </div>
  <div>
    <%== pagy_bootstrap_nav(@pagy) %>
    <%== pagy_limit_selector_js(@pagy, item_name: "Book stock".pluralize(@pagy.count), id: "pagy-limit-selector") %>
    <%= link_to(
          t("view.index.update_item_per_page", model: BookStock.model_name.human),
          "javascript:void(0);",
          onClick: "updateItemPerPage(arguments[0],
          this)"
        ) %>
  </div>
<% end %>
  </main>
</div>

app/views/book_stocks/new.html.erb
<h1><%= t("view.new.title", model: BookStock.model_name.human) %></h1>
<%= render "form", book_stock: @book_stock %>

<br>

<div>
  <%= link_to t("view.new.move_to_index", model: BookStock.model_name.human.pluralize), book_stocks_path %>
</div>

app/views/book_stocks/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= BookStock.model_name.human %></h1>

<%= render @book_stock %>

<div>
  <%= link_to t("view.show.move_to_update", model: BookStock.model_name.human), edit_book_stock_path(@book_stock) %> |
  <%= link_to t("view.show.move_to_index", model: BookStock.model_name.human.pluralize), book_stocks_path %>

  <%= button_to t("helpers.submit.delete"),
                @book_stock,
                method: :delete,
                class: %w[btn btn-primary],
                data: { turbo_confirm: t("helpers.dialog.delete", id: @book_stock.id) } %>
</div>