config/routes.rb
Rails.application.routes.draw do
  resources :lending_sets
  resources :lending_statuses
  resources :customers
  resources :customers, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :book_stocks, except: %w[export] do
    collection { get :export }
  end
  resources :book_stocks
  resources :book_stocks, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :book_stock_statuses
  resources :authors
  resources :authors, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :book_masters
  resources :book_masters, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :ndc_categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/book_master.rb
class BookMaster < ApplicationRecord
  include CsvImportable

  def self.ransackable_attributes(_auth_object = nil)
    %w[isbn title publication_date ndc_category_id author_id id created_at updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[authors book_author_relationship ndc_category]
  end

  # TODO: ちゃんとした判定ロジックを作る
  VALID_ISBN_PATTERN = /[0-9\-]+/

  validates :isbn, presence: true, uniqueness: true, format: { with: VALID_ISBN_PATTERN }
  validates :title, presence: true
  validates :publication_date, presence: true
  validates :ndc_category, presence: true

  belongs_to :ndc_category
  has_many :book_author_relationship
  has_many :authors, through: :book_author_relationship
end

app/controllers/book_masters_controller.rb
class BookMastersController < ApplicationController
  include Pagy::Backend
  before_action :set_book_master, only: %i[show edit update destroy]

  # GET /book_masters
  def index
    @book_masters = BookMaster
      .eager_load(:ndc_category)
    @q = @book_masters.ransack(params[:q])
    @q.sorts = "id asc" if @q.sorts.empty?
    @pagy, @book_masters = pagy(@q.result, page: params[:page], items: params[:items])
  end

  # GET /book_masters/1
  def show
  end

  # GET /book_masters/new
  def new
    @book_master = BookMaster.new
  end

  # GET /book_masters/1/edit
  def edit
  end

  # POST /book_masters
  def create
    @book_master = BookMaster.new(book_master_params)

    if @book_master.save
      redirect_to @book_master, notice: t("controller.create.success", model: BookMaster.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /book_masters/1
  def update
    if @book_master.update(book_master_params)
      redirect_to @book_master, notice: t("controller.edit.success", model: BookMaster.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /book_masters/1
  def destroy
    @book_master.destroy!
    redirect_to book_masters_url, notice: t("controller.destroy.success", model: BookMaster.model_name.human)
  end

  # POST /book_masters_bulk_insert
  def bulk_insert
    if params[:file].nil?
      redirect_to book_masters_url
      return
    end

    errors = BookMaster.csv_import(
      params[:file],
      parser,
      { "タイトル" => "title", "ISBN" => "isbn", "著者" => "author_ids", "発行日" => "publication_date", "書籍分類" => "ndc_category_id"},
      {},
      {"著者" => { parent: Author, search_column_name: :name, is_many: true}, "書籍分類" => { parent: NdcCategory, search_column_name: :name}}
    )

    if errors.empty?
      flash.notice = t("controller.create.success", model: BookMaster.model_name.human)
    else
      flash.alert = errors
    end

    redirect_to book_masters_url
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_book_master
      @book_master = BookMaster
        .eager_load(:ndc_category)
        .find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_master_params
      params.require(:book_master).permit(:isbn, :title, :publication_date, :ndc_category_id, { author_ids: [] })
    end

    def parser
      Csv::CsvParser
    end
end

app/helpers/book_masters_helper.rb
module BookMastersHelper
  include Pagy::Frontend
end

app/views/book_masters/_book_master.html.erb
<div id="<%= dom_id book_master %>">
  <table class="table table-hover">
    <tr>
      <td>
        <strong>Id:</strong>
      </td>
      <td>
        <%= book_master.id %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= BookMaster.human_attribute_name(:isbn) %>
        </strong>
      </td>
      <td>
        <%= book_master.isbn %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= BookMaster.human_attribute_name(:title) %>
        </strong>
      </td>
      <td>
        <%= book_master.title %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= BookMaster.human_attribute_name(:author) %>
        </strong>
      </td>
      <td>
        <%= book_master.authors.map{|a| a.name}.join(", ") %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= BookMaster.human_attribute_name(:publication_date) %>
        </strong>
      </td>
      <td>
        <%= book_master.publication_date && l(book_master.publication_date) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= BookMaster.human_attribute_name(:ndc_category_id) %>
        </strong>
      </td>
      <td>
        <%= book_master.ndc_category.name %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= BookMaster.human_attribute_name(:created_at) %>
        </strong>
      </td>
      <td>
        <%= book_master.created_at && l(book_master.created_at) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= BookMaster.human_attribute_name(:updated_at) %>
        </strong>
      </td>
      <td>
        <%= book_master.updated_at && l(book_master.updated_at) %>
      </td>
    </tr>
  </table>
</div>

app/views/book_masters/_form.html.erb
<%= form_with(model: book_master, html: { class: %w[form-control form-control-sm] }) do |form| -%>
  <%- if book_master.errors.any? -%>
  <div style="color: red">
    <h2><%= t("errors.template.header", model: BookMaster.model_name.human, count: book_master.errors.count) %></h2>

    <ul>
    <% book_master.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <%- end -%>
    </ul>
  </div>
  <%- end -%>

  <%- if book_master.persisted? -%>
  <div>
    <%= form.label :id, style: "display: block" %>
    <div class="ps-2">
      <%= form.number_field :id, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <%- end -%>
  <div>
    <%= form.label :isbn, style: "display: block" %>
    <div class="ps-2">
      <%= form.text_field :isbn, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <div>
    <%= form.label :title, style: "display: block" %>
    <div class="ps-2">
      <%= form.text_field :title, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <div>
    <%= form.label :publication_date, style: "display: block" %>
    <div class="ps-2">
      <%= form.date_field :publication_date, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <div>
    <%= form.label BookMaster.reflect_on_association(:ndc_category).foreign_key %>
    <div class="ps-2">
      <%= form.collection_select(
            BookMaster.reflect_on_association(:ndc_category).foreign_key,
            BookMaster.reflect_on_association(:ndc_category).klass.all,
            :id,
            :name,
            { include_blank: "選択なし" }
          ) %>
    </div>
  </div>
  <div>
    <%= form.label :author %>
    <div class="ps-2">
      <%= form.collection_select(
            :author_ids,
            Author.all,
            :id,
            :name,
            { multiple: true }
          ) %>
    </div>
  </div>
  <%- if book_master.persisted? -%>
  <div>
    <%= form.label :created_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :created_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <div>
    <%= form.label :updated_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :updated_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <%- end -%>
  <div>
    <%= form.submit class: %w[btn btn-primary] %>
  </div>
<% end %>

app/views/book_masters/edit.html.erb
<h1><%= t("view.edit.title", model: BookMaster.model_name.human) %></h1>
<%= render "form", book_master: @book_master %>

<br>

<div>
  <%= link_to t("view.edit.move_to_show", model: BookMaster.model_name.human), @book_master %> |
  <%= link_to t("view.edit.move_to_index", model: BookMaster.model_name.human.pluralize), book_masters_path %>
</div>

app/views/book_masters/index.html.erb
<div style="display: flex;flex-direction: column;height: 100vh;">

  <header class="main-content-header">
    <p style="color: green"><%= notice %></p>

    <h1><%= BookMaster.model_name.human %><%= link_to "", new_book_master_path, class: %w[bi bi-plus-circle-fill ms-2] %></h1>

    <div id="flashes">
      <%= render partial: "flash", locals: {model: Author} %>
    </div>

    <%= form_tag bulk_insert_book_masters_path, multipart: true do %>
      <%= label_tag "CSVインポート:" %>
      <%= file_field_tag :file, accept: "text/csv" %>
      <%= submit_tag "インポート", class: %w[btn btn-primary] %>
    <% end %>

  <div class="accordion">
    <div class="accordion-item">
      <h2 class="accordion-header" id="search-form-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#search-form"
          aria-expanded="false"
          aria-controls="search-form"><%= t("view.index.search_condition") %></button>
      </h2>
      <div id="search-form" class="panel panel-default accordion-collapse collapse" aria-labelledby="headingOne">
<%= search_form_for @q, html: { class: %w[form-control form-control-sm], data: { turbo_frame: "list" } } do |f| %>
        <div>
          <%= f.label :id_eq %>
          <div class="ps-2">
            <%= f.number_field :id_eq, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :isbn_cont %>
          <div class="ps-2">
            <%= f.search_field :isbn_cont, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :title_cont %>
          <div class="ps-2">
            <%= f.search_field :title_cont, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :author.to_s + "_in".to_s %>
          <div class="ps-2">
            <%= f.collection_select(
                  :book_author_relationship_author_id.to_s + "_in".to_s,
                  Author.all,
                  :id,
                  :name,
                  {},
                  { multiple: true }
                ) %>
          </div>
        </div>
        <div>
          <%= f.label :publication_date %>
          <div class="ps-2">
            <%= f.date_field :publication_date_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.date_field :publication_date_lteq_end_of_day, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label BookMaster.reflect_on_association(:ndc_category).foreign_key + "_in".to_s %>
          <div class="ps-2">
            <%= f.collection_select(
                  BookMaster.reflect_on_association(:ndc_category).foreign_key + "_in".to_s,
                  BookMaster.reflect_on_association(:ndc_category).klass.all,
                  :id,
                  :name,
                  {},
                  { multiple: true }
                ) %>
          </div>
        </div>
        <div>
          <%= f.label :created_at %>
          <div class="ps-2">
            <%= f.datetime_field :created_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :created_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :updated_at %>
          <div class="ps-2">
            <%= f.datetime_field :updated_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :updated_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <%= f.hidden_field :limit, id: "f-limit", value: params[:limit] || Pagy::DEFAULT[:limit] %>
        <%= f.submit class: %w[btn btn-primary] %>
        <input
          type="reset"
          class="btn btn-primary"
          onclick="clear_form(arguments[0], this)"
          value="<%= t("helpers.submit.clear") %>">
<%- end -%>
      </div>
    </div>
  </header>

  <main style="flex-grow: 1;flex-shrink: 1;overflow-y: auto;">
<%= turbo_frame_tag "list" do %>
  <div id="book_masters" class="text-nowrap">
    <table class="table table-hover text-nowrap">
      <thead class="table-light sticky-top">
        <th><%= sort_link(@q, :id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :isbn, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :title, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :author, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :publication_date, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :ndc_category_id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :created_at, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :updated_at, default_order: :asc, class: "d-block") %></th>
        <th><%= t("view.index.operation") %></th>
      </thead>
      <tbody>
  <%- @book_masters.each do |book_master| %>
        <tr
          tabindex="0"
          role="button"
          onkeypress="handleEnterKeypressListIten(arguments[0], this, '<%= url_target(nil, book_master).to_s %>')"
          onclick="handleClickListItem(arguments[0], this, '<%= url_target(nil, book_master).to_s %>')">
          <td><%= book_master.id %></td>
          <td><%= book_master.isbn %></td>
          <td><%= book_master.title %></td>
          <td><%= book_master.authors.map{|author| author.name }.join(", ") %></td>
          <td><%= book_master.publication_date && l(book_master.publication_date) %></td>
          <td><%= book_master.ndc_category.name %></td>
          <td><%= book_master.created_at && l(book_master.created_at) %></td>
          <td><%= book_master.updated_at && l(book_master.updated_at) %></td>
          <td>
            <%= button_to(
                  t("helpers.submit.delete"),
                  book_master,
                  method: :delete,
                  tabindex: 0,
                  class: %w[btn btn-primary],
                  onclick: "handleDeleteListItem(arguments[0], this)",
                  data: { turbo_confirm: t("helpers.dialog.delete", id: book_master.id) }
                ) %>
          </td>
        </tr>
  <%- end %>
      </tbody>
    </table>
  </div>
  <div>
    <%== pagy_bootstrap_nav(@pagy) %>
    <%== pagy_limit_selector_js(@pagy, item_name: "Book master".pluralize(@pagy.count), id: "pagy-limit-selector") %>
    <%= link_to(
          t("view.index.update_item_per_page", model: BookMaster.model_name.human),
          "javascript:void(0);",
          onClick: "updateItemPerPage(arguments[0],
          this)"
        ) %>
  </div>
<% end %>
  </main>
</div>

app/views/book_masters/new.html.erb
<h1><%= t("view.new.title", model: BookMaster.model_name.human) %></h1>
<%= render "form", book_master: @book_master %>

<br>

<div>
  <%= link_to t("view.new.move_to_index", model: BookMaster.model_name.human.pluralize), book_masters_path %>
</div>

app/views/book_masters/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= BookMaster.model_name.human %></h1>

<%= render @book_master %>

<div>
  <%= link_to t("view.show.move_to_update", model: BookMaster.model_name.human), edit_book_master_path(@book_master) %> |
  <%= link_to t("view.show.move_to_index", model: BookMaster.model_name.human.pluralize), book_masters_path %>

  <%= button_to t("helpers.submit.delete"),
                @book_master,
                method: :delete,
                class: %w[btn btn-primary],
                data: { turbo_confirm: t("helpers.dialog.delete", id: @book_master.id) } %>
</div>