config/routes.rb
Rails.application.routes.draw do
  resources :lending_sets
  resources :lending_statuses
  resources :customers
  resources :customers, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :book_stocks, except: %w[export] do
    collection { get :export }
  end
  resources :book_stocks
  resources :book_stocks, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :book_stock_statuses
  resources :authors
  resources :authors, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :book_masters
  resources :book_masters, except: %w[import] do
    collection { post :bulk_insert }
  end
  resources :ndc_categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/lending_statuses_controller.rb
class LendingStatusesController < ApplicationController
  include Pagy::Backend
  before_action :set_lending_status, only: %i[show edit update destroy]

  # GET /lending_statuses
  def index
    @lending_statuses = LendingStatus
      .all
    @q = @lending_statuses.ransack(params[:q])
    @q.sorts = "id asc" if @q.sorts.empty?
    @pagy, @lending_statuses = pagy(@q.result, page: params[:page], items: params[:items])
  end

  # GET /lending_statuses/1
  def show
  end

  # GET /lending_statuses/new
  def new
    @lending_status = LendingStatus.new
  end

  # GET /lending_statuses/1/edit
  def edit
  end

  # POST /lending_statuses
  def create
    @lending_status = LendingStatus.new(lending_status_params)

    if @lending_status.save
      redirect_to @lending_status, notice: t("controller.create.success", model: LendingStatus.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /lending_statuses/1
  def update
    if @lending_status.update(lending_status_params)
      redirect_to @lending_status, notice: t("controller.edit.success", model: LendingStatus.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /lending_statuses/1
  def destroy
    @lending_status.destroy!
    redirect_to lending_statuses_url, notice: t("controller.destroy.success", model: LendingStatus.model_name.human)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_lending_status
      @lending_status = LendingStatus
        .find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lending_status_params
      params.require(:lending_status).permit(:name)
    end
end

app/helpers/lending_statuses_helper.rb
module LendingStatusesHelper
  include Pagy::Frontend
end

app/views/lending_statuses/_form.html.erb
<%= form_with(model: lending_status, html: { class: %w[form-control form-control-sm] }) do |form| -%>
  <%- if lending_status.errors.any? -%>
  <div style="color: red">
    <h2><%= t("errors.template.header", model: LendingStatus.model_name.human, count: lending_status.errors.count) %></h2>

    <ul>
    <% lending_status.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <%- end -%>
    </ul>
  </div>
  <%- end -%>

  <%- if lending_status.persisted? -%>
  <div>
    <%= form.label :id, style: "display: block" %>
    <div class="ps-2">
      <%= form.number_field :id, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <%- end -%>
  <div>
    <%= form.label :name, style: "display: block" %>
    <div class="ps-2">
      <%= form.text_field :name, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <%- if lending_status.persisted? -%>
  <div>
    <%= form.label :created_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :created_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <div>
    <%= form.label :updated_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :updated_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <%- end -%>
  <div>
    <%= form.submit class: %w[btn btn-primary] %>
  </div>
<% end %>

app/views/lending_statuses/_lending_status.html.erb
<div id="<%= dom_id lending_status %>">
  <table class="table table-hover">
    <tr>
      <td>
        <strong>Id:</strong>
      </td>
      <td>
        <%= lending_status.id %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= LendingStatus.human_attribute_name(:name) %>
        </strong>
      </td>
      <td>
        <%= lending_status.name %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= LendingStatus.human_attribute_name(:created_at) %>
        </strong>
      </td>
      <td>
        <%= lending_status.created_at && l(lending_status.created_at) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= LendingStatus.human_attribute_name(:updated_at) %>
        </strong>
      </td>
      <td>
        <%= lending_status.updated_at && l(lending_status.updated_at) %>
      </td>
    </tr>
  </table>
</div>

app/views/lending_statuses/edit.html.erb
<h1><%= t("view.edit.title", model: LendingStatus.model_name.human) %></h1>
<%= render "form", lending_status: @lending_status %>

<br>

<div>
  <%= link_to t("view.edit.move_to_show", model: LendingStatus.model_name.human), @lending_status %> |
  <%= link_to t("view.edit.move_to_index", model: LendingStatus.model_name.human.pluralize), lending_statuses_path %>
</div>

app/views/lending_statuses/index.html.erb
<div style="display: flex;flex-direction: column;height: 100vh;">

  <header class="main-content-header">
    <p style="color: green"><%= notice %></p>

    <h1><%= LendingStatus.model_name.human %><%= link_to "", new_lending_status_path, class: %w[bi bi-plus-circle-fill ms-2] %></h1>

  <div class="accordion">
    <div class="accordion-item">
      <h2 class="accordion-header" id="search-form-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#search-form"
          aria-expanded="false"
          aria-controls="search-form"><%= t("view.index.search_condition") %></button>
      </h2>
      <div id="search-form" class="panel panel-default accordion-collapse collapse" aria-labelledby="headingOne">
<%= search_form_for @q, html: { class: %w[form-control form-control-sm], data: { turbo_frame: "list" } } do |f| %>
        <div>
          <%= f.label :id_eq %>
          <div class="ps-2">
            <%= f.number_field :id_eq, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :name_cont %>
          <div class="ps-2">
            <%= f.search_field :name_cont, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :created_at %>
          <div class="ps-2">
            <%= f.datetime_field :created_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :created_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :updated_at %>
          <div class="ps-2">
            <%= f.datetime_field :updated_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :updated_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <%= f.hidden_field :limit, id: "f-limit", value: params[:limit] || Pagy::DEFAULT[:limit] %>
        <%= f.submit class: %w[btn btn-primary] %>
        <input
          type="reset"
          class="btn btn-primary"
          onclick="clear_form(arguments[0], this)"
          value="<%= t("helpers.submit.clear") %>">
<%- end -%>
      </div>
    </div>
  </header>

  <main style="flex-grow: 1;flex-shrink: 1;overflow-y: auto;">
<%= turbo_frame_tag "list" do %>
  <div id="lending_statuses" class="text-nowrap">
    <table class="table table-hover text-nowrap">
      <thead class="table-light sticky-top">
        <th><%= sort_link(@q, :id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :name, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :created_at, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :updated_at, default_order: :asc, class: "d-block") %></th>
        <th><%= t("view.index.operation") %></th>
      </thead>
      <tbody>
  <%- @lending_statuses.each do |lending_status| %>
        <tr
          tabindex="0"
          role="button"
          onkeypress="handleEnterKeypressListIten(arguments[0], this, '<%= url_target(nil, lending_status).to_s %>')"
          onclick="handleClickListItem(arguments[0], this, '<%= url_target(nil, lending_status).to_s %>')">
          <td><%= lending_status.id %></td>
          <td><%= lending_status.name %></td>
          <td><%= lending_status.created_at && l(lending_status.created_at) %></td>
          <td><%= lending_status.updated_at && l(lending_status.updated_at) %></td>
          <td>
            <%= button_to(
                  t("helpers.submit.delete"),
                  lending_status,
                  method: :delete,
                  tabindex: 0,
                  class: %w[btn btn-primary],
                  onclick: "handleDeleteListItem(arguments[0], this)",
                  data: { turbo_confirm: t("helpers.dialog.delete", id: lending_status.id) }
                ) %>
          </td>
        </tr>
  <%- end %>
      </tbody>
    </table>
  </div>
  <div>
    <%== pagy_bootstrap_nav(@pagy) %>
    <%== pagy_limit_selector_js(@pagy, item_name: "Lending status".pluralize(@pagy.count), id: "pagy-limit-selector") %>
    <%= link_to(
          t("view.index.update_item_per_page", model: LendingStatus.model_name.human),
          "javascript:void(0);",
          onClick: "updateItemPerPage(arguments[0],
          this)"
        ) %>
  </div>
<% end %>
  </main>
</div>

app/views/lending_statuses/new.html.erb
<h1><%= t("view.new.title", model: LendingStatus.model_name.human) %></h1>
<%= render "form", lending_status: @lending_status %>

<br>

<div>
  <%= link_to t("view.new.move_to_index", model: LendingStatus.model_name.human.pluralize), lending_statuses_path %>
</div>

app/views/lending_statuses/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= LendingStatus.model_name.human %></h1>

<%= render @lending_status %>

<div>
  <%= link_to t("view.show.move_to_update", model: LendingStatus.model_name.human), edit_lending_status_path(@lending_status) %> |
  <%= link_to t("view.show.move_to_index", model: LendingStatus.model_name.human.pluralize), lending_statuses_path %>

  <%= button_to t("helpers.submit.delete"),
                @lending_status,
                method: :delete,
                class: %w[btn btn-primary],
                data: { turbo_confirm: t("helpers.dialog.delete", id: @lending_status.id) } %>
</div>